// AUTO-GENERATED by scripts/sync-cloudinary.mjs — do not edit by hand.
// Run `npm run sync` to refresh.

export type CldAsset = {
  publicId: string;
  folder: string;
  type: "image" | "video";
  width: number | null;
  height: number | null;
  bytes: number | null;
  createdAt: string | null;
};

export const cldAssets: CldAsset[] = [
  {
    "publicId": "sample",
    "folder": "",
    "type": "image",
    "width": 864,
    "height": 576,
    "bytes": 120253,
    "createdAt": "2026-05-09T07:50:19Z"
  },
  {
    "publicId": "samples/cloudinary-logo-vector",
    "folder": "samples",
    "type": "image",
    "width": 1000,
    "height": 320,
    "bytes": 5961,
    "createdAt": "2026-05-09T07:50:28Z"
  },
  {
    "publicId": "samples/food/dessert",
    "folder": "samples/food",
    "type": "image",
    "width": 1220,
    "height": 813,
    "bytes": 125888,
    "createdAt": "2026-05-09T07:50:28Z"
  },
  {
    "publicId": "samples/ecommerce/analog-classic",
    "folder": "samples/ecommerce",
    "type": "image",
    "width": 1280,
    "height": 853,
    "bytes": 72558,
    "createdAt": "2026-05-09T07:50:28Z"
  },
  {
    "publicId": "samples/cloudinary-icon",
    "folder": "samples",
    "type": "image",
    "width": 1000,
    "height": 1000,
    "bytes": 57334,
    "createdAt": "2026-05-09T07:50:28Z"
  },
  {
    "publicId": "samples/animals/cat",
    "folder": "samples/animals",
    "type": "image",
    "width": 768,
    "height": 1024,
    "bytes": 92690,
    "createdAt": "2026-05-09T07:50:29Z"
  },
  {
    "publicId": "samples/food/pot-mussels",
    "folder": "samples/food",
    "type": "image",
    "width": 1220,
    "height": 818,
    "bytes": 191852,
    "createdAt": "2026-05-09T07:50:30Z"
  },
  {
    "publicId": "samples/food/fish-vegetables",
    "folder": "samples/food",
    "type": "image",
    "width": 1220,
    "height": 813,
    "bytes": 169013,
    "createdAt": "2026-05-09T07:50:30Z"
  },
  {
    "publicId": "samples/animals/reindeer",
    "folder": "samples/animals",
    "type": "image",
    "width": 1220,
    "height": 813,
    "bytes": 161150,
    "createdAt": "2026-05-09T07:50:30Z"
  },
  {
    "publicId": "samples/landscapes/girl-urban-view",
    "folder": "samples/landscapes",
    "type": "image",
    "width": 2048,
    "height": 1252,
    "bytes": 372778,
    "createdAt": "2026-05-09T07:50:31Z"
  },
  {
    "publicId": "samples/people/kitchen-bar",
    "folder": "samples/people",
    "type": "image",
    "width": 1220,
    "height": 813,
    "bytes": 154151,
    "createdAt": "2026-05-09T07:50:31Z"
  },
  {
    "publicId": "samples/sheep",
    "folder": "samples",
    "type": "image",
    "width": 1600,
    "height": 1067,
    "bytes": 269304,
    "createdAt": "2026-05-09T07:50:31Z"
  },
  {
    "publicId": "samples/people/smiling-man",
    "folder": "samples/people",
    "type": "image",
    "width": 849,
    "height": 565,
    "bytes": 338794,
    "createdAt": "2026-05-09T07:50:32Z"
  },
  {
    "publicId": "samples/people/boy-snow-hoodie",
    "folder": "samples/people",
    "type": "image",
    "width": 1777,
    "height": 1332,
    "bytes": 581238,
    "createdAt": "2026-05-09T07:50:32Z"
  },
  {
    "publicId": "samples/bike",
    "folder": "samples",
    "type": "image",
    "width": 2000,
    "height": 1333,
    "bytes": 475687,
    "createdAt": "2026-05-09T07:50:32Z"
  },
  {
    "publicId": "samples/ecommerce/shoes",
    "folder": "samples/ecommerce",
    "type": "image",
    "width": 587,
    "height": 507,
    "bytes": 393265,
    "createdAt": "2026-05-09T07:50:32Z"
  },
  {
    "publicId": "samples/people/jazz",
    "folder": "samples/people",
    "type": "image",
    "width": 3000,
    "height": 1993,
    "bytes": 695548,
    "createdAt": "2026-05-09T07:50:33Z"
  },
  {
    "publicId": "samples/ecommerce/car-interior-design",
    "folder": "samples/ecommerce",
    "type": "image",
    "width": 2000,
    "height": 2667,
    "bytes": 1254103,
    "createdAt": "2026-05-09T07:50:34Z"
  },
  {
    "publicId": "samples/landscapes/beach-boat",
    "folder": "samples/landscapes",
    "type": "image",
    "width": 2600,
    "height": 1950,
    "bytes": 1235823,
    "createdAt": "2026-05-09T07:50:34Z"
  },
  {
    "publicId": "samples/animals/three-dogs",
    "folder": "samples/animals",
    "type": "image",
    "width": 2700,
    "height": 1800,
    "bytes": 854929,
    "createdAt": "2026-05-09T07:50:34Z"
  },
  {
    "publicId": "samples/people/bicycle",
    "folder": "samples/people",
    "type": "image",
    "width": 2889,
    "height": 1926,
    "bytes": 1130015,
    "createdAt": "2026-05-09T07:50:34Z"
  },
  {
    "publicId": "samples/landscapes/architecture-signs",
    "folder": "samples/landscapes",
    "type": "image",
    "width": 3000,
    "height": 2000,
    "bytes": 945255,
    "createdAt": "2026-05-09T07:50:34Z"
  },
  {
    "publicId": "samples/imagecon-group",
    "folder": "samples",
    "type": "image",
    "width": 2800,
    "height": 1867,
    "bytes": 1487070,
    "createdAt": "2026-05-09T07:50:35Z"
  },
  {
    "publicId": "samples/ecommerce/accessories-bag",
    "folder": "samples/ecommerce",
    "type": "image",
    "width": 3000,
    "height": 2000,
    "bytes": 1459256,
    "createdAt": "2026-05-09T07:50:35Z"
  },
  {
    "publicId": "samples/landscapes/nature-mountains",
    "folder": "samples/landscapes",
    "type": "image",
    "width": 3000,
    "height": 2000,
    "bytes": 3171453,
    "createdAt": "2026-05-09T07:50:36Z"
  },
  {
    "publicId": "samples/ecommerce/leather-bag-gray",
    "folder": "samples/ecommerce",
    "type": "image",
    "width": 2385,
    "height": 1590,
    "bytes": 1323582,
    "createdAt": "2026-05-09T07:50:36Z"
  },
  {
    "publicId": "samples/food/spices",
    "folder": "samples/food",
    "type": "image",
    "width": 2000,
    "height": 2000,
    "bytes": 2129950,
    "createdAt": "2026-05-09T07:50:36Z"
  },
  {
    "publicId": "samples/landscapes/landscape-panorama",
    "folder": "samples/landscapes",
    "type": "image",
    "width": 10906,
    "height": 2349,
    "bytes": 7858062,
    "createdAt": "2026-05-09T07:50:37Z"
  },
  {
    "publicId": "samples/cloudinary-group",
    "folder": "samples",
    "type": "image",
    "width": 3000,
    "height": 1526,
    "bytes": 2856169,
    "createdAt": "2026-05-09T07:50:37Z"
  },
  {
    "publicId": "samples/animals/kitten-playing",
    "folder": "samples/animals",
    "type": "image",
    "width": 320,
    "height": 180,
    "bytes": 6620002,
    "createdAt": "2026-05-09T07:50:38Z"
  },
  {
    "publicId": "samples/sea-turtle",
    "folder": "samples",
    "type": "video",
    "width": 1920,
    "height": 1080,
    "bytes": 27932506,
    "createdAt": "2026-05-09T07:50:38Z"
  },
  {
    "publicId": "samples/elephants",
    "folder": "samples",
    "type": "video",
    "width": 1920,
    "height": 1080,
    "bytes": 38855178,
    "createdAt": "2026-05-09T07:50:38Z"
  },
  {
    "publicId": "samples/cld-sample-video",
    "folder": "samples",
    "type": "video",
    "width": 3840,
    "height": 2160,
    "bytes": 35988643,
    "createdAt": "2026-05-09T07:50:39Z"
  },
  {
    "publicId": "samples/dance-2",
    "folder": "samples",
    "type": "video",
    "width": 3840,
    "height": 2160,
    "bytes": 22373558,
    "createdAt": "2026-05-09T07:50:39Z"
  },
  {
    "publicId": "samples/two-ladies",
    "folder": "samples",
    "type": "image",
    "width": 1500,
    "height": 1200,
    "bytes": 211712,
    "createdAt": "2026-05-09T07:50:40Z"
  },
  {
    "publicId": "samples/shoe",
    "folder": "samples",
    "type": "image",
    "width": 1000,
    "height": 1140,
    "bytes": 72888,
    "createdAt": "2026-05-09T07:50:41Z"
  },
  {
    "publicId": "samples/balloons",
    "folder": "samples",
    "type": "image",
    "width": 1000,
    "height": 667,
    "bytes": 117237,
    "createdAt": "2026-05-09T07:50:42Z"
  },
  {
    "publicId": "samples/smile",
    "folder": "samples",
    "type": "image",
    "width": 1552,
    "height": 1000,
    "bytes": 657749,
    "createdAt": "2026-05-09T07:50:44Z"
  },
  {
    "publicId": "samples/breakfast",
    "folder": "samples",
    "type": "image",
    "width": 2447,
    "height": 2196,
    "bytes": 3024938,
    "createdAt": "2026-05-09T07:50:45Z"
  },
  {
    "publicId": "samples/man-on-a-escalator",
    "folder": "samples",
    "type": "image",
    "width": 1340,
    "height": 1340,
    "bytes": 563708,
    "createdAt": "2026-05-09T07:50:46Z"
  },
  {
    "publicId": "samples/look-up",
    "folder": "samples",
    "type": "image",
    "width": 900,
    "height": 900,
    "bytes": 414964,
    "createdAt": "2026-05-09T07:50:46Z"
  },
  {
    "publicId": "samples/man-on-a-street",
    "folder": "samples",
    "type": "image",
    "width": 1340,
    "height": 1340,
    "bytes": 564013,
    "createdAt": "2026-05-09T07:50:47Z"
  },
  {
    "publicId": "samples/outdoor-woman",
    "folder": "samples",
    "type": "image",
    "width": 640,
    "height": 963,
    "bytes": 93473,
    "createdAt": "2026-05-09T07:50:47Z"
  },
  {
    "publicId": "samples/chair",
    "folder": "samples",
    "type": "image",
    "width": 800,
    "height": 600,
    "bytes": 130488,
    "createdAt": "2026-05-09T07:50:48Z"
  },
  {
    "publicId": "samples/chair-and-coffee-table",
    "folder": "samples",
    "type": "image",
    "width": 1001,
    "height": 1500,
    "bytes": 64504,
    "createdAt": "2026-05-09T07:50:48Z"
  },
  {
    "publicId": "samples/dessert-on-a-plate",
    "folder": "samples",
    "type": "image",
    "width": 1200,
    "height": 1200,
    "bytes": 348717,
    "createdAt": "2026-05-09T07:50:49Z"
  },
  {
    "publicId": "samples/cup-on-a-table",
    "folder": "samples",
    "type": "image",
    "width": 2246,
    "height": 1500,
    "bytes": 134300,
    "createdAt": "2026-05-09T07:50:49Z"
  },
  {
    "publicId": "samples/man-portrait",
    "folder": "samples",
    "type": "image",
    "width": 1333,
    "height": 2000,
    "bytes": 505607,
    "createdAt": "2026-05-09T07:50:49Z"
  },
  {
    "publicId": "samples/upscale-face-1",
    "folder": "samples",
    "type": "image",
    "width": 233,
    "height": 233,
    "bytes": 18110,
    "createdAt": "2026-05-09T07:50:50Z"
  },
  {
    "publicId": "samples/coffee",
    "folder": "samples",
    "type": "image",
    "width": 1920,
    "height": 1280,
    "bytes": 165287,
    "createdAt": "2026-05-09T07:50:50Z"
  },
  {
    "publicId": "samples/woman-on-a-football-field",
    "folder": "samples",
    "type": "image",
    "width": 1200,
    "height": 1350,
    "bytes": 416598,
    "createdAt": "2026-05-09T07:50:51Z"
  },
  {
    "publicId": "samples/radial",
    "folder": "samples",
    "type": "image",
    "width": 950,
    "height": 640,
    "bytes": 4503,
    "createdAt": "2026-05-09T07:50:51Z"
  },
  {
    "publicId": "samples/canvas",
    "folder": "samples",
    "type": "image",
    "width": 600,
    "height": 388,
    "bytes": 61928,
    "createdAt": "2026-05-09T07:50:51Z"
  },
  {
    "publicId": "samples/logo",
    "folder": "samples",
    "type": "image",
    "width": 480,
    "height": 314,
    "bytes": 10897,
    "createdAt": "2026-05-09T07:50:51Z"
  },
  {
    "publicId": "samples/paper",
    "folder": "samples",
    "type": "image",
    "width": 1024,
    "height": 1024,
    "bytes": 1440561,
    "createdAt": "2026-05-09T07:50:52Z"
  },
  {
    "publicId": "samples/zoom",
    "folder": "samples",
    "type": "image",
    "width": 484,
    "height": 324,
    "bytes": 2863,
    "createdAt": "2026-05-09T07:50:52Z"
  },
  {
    "publicId": "cld-sample",
    "folder": "",
    "type": "image",
    "width": 1870,
    "height": 1250,
    "bytes": 476846,
    "createdAt": "2026-05-09T07:50:53Z"
  },
  {
    "publicId": "cld-sample-2",
    "folder": "",
    "type": "image",
    "width": 1870,
    "height": 1250,
    "bytes": 592235,
    "createdAt": "2026-05-09T07:50:53Z"
  },
  {
    "publicId": "samples/waves",
    "folder": "samples",
    "type": "image",
    "width": 1024,
    "height": 1024,
    "bytes": 1563444,
    "createdAt": "2026-05-09T07:50:53Z"
  },
  {
    "publicId": "samples/radial_02",
    "folder": "samples",
    "type": "image",
    "width": 427,
    "height": 271,
    "bytes": 123165,
    "createdAt": "2026-05-09T07:50:53Z"
  },
  {
    "publicId": "cld-sample-4",
    "folder": "",
    "type": "image",
    "width": 1870,
    "height": 1250,
    "bytes": 818600,
    "createdAt": "2026-05-09T07:50:54Z"
  },
  {
    "publicId": "cld-sample-3",
    "folder": "",
    "type": "image",
    "width": 1870,
    "height": 1250,
    "bytes": 905834,
    "createdAt": "2026-05-09T07:50:54Z"
  },
  {
    "publicId": "cld-sample-5",
    "folder": "",
    "type": "image",
    "width": 1870,
    "height": 1250,
    "bytes": 379132,
    "createdAt": "2026-05-09T07:50:55Z"
  },
  {
    "publicId": "main-sample",
    "folder": "",
    "type": "image",
    "width": 1248,
    "height": 832,
    "bytes": 1868954,
    "createdAt": "2026-05-09T07:50:55Z"
  },
  {
    "publicId": "IMG_6339_tn4m30",
    "folder": "Trips",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 391867,
    "createdAt": "2026-05-09T12:28:47Z"
  },
  {
    "publicId": "IMG_4845_eyircm",
    "folder": "In Her Element",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 2632743,
    "createdAt": "2026-05-09T12:28:51Z"
  },
  {
    "publicId": "IMG_6349_umlt22",
    "folder": "Trips",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 420869,
    "createdAt": "2026-05-09T12:28:59Z"
  },
  {
    "publicId": "ca418172-a635-4b48-9e5b-b18e6b32e809_ruwmeq",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1200,
    "height": 1600,
    "bytes": 203921,
    "createdAt": "2026-05-09T12:29:03Z"
  },
  {
    "publicId": "IMG_4839_jrao72",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1987418,
    "createdAt": "2026-05-09T12:29:31Z"
  },
  {
    "publicId": "IMG_6350_hzvbng",
    "folder": "Trips",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 426834,
    "createdAt": "2026-05-09T12:29:34Z"
  },
  {
    "publicId": "IMG_6352_xodozr",
    "folder": "In Her Element",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 324866,
    "createdAt": "2026-05-09T12:29:34Z"
  },
  {
    "publicId": "IMG_6026_famoxy",
    "folder": "Where it All Began",
    "type": "image",
    "width": 2208,
    "height": 1244,
    "bytes": 477446,
    "createdAt": "2026-05-09T12:29:37Z"
  },
  {
    "publicId": "66b1a769-d856-4654-ba7c-3c53a5b4ec15_lsxmsk",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1600,
    "height": 1200,
    "bytes": 381549,
    "createdAt": "2026-05-09T12:29:37Z"
  },
  {
    "publicId": "IMG_6353_v9a40f",
    "folder": "In Her Element",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 329783,
    "createdAt": "2026-05-09T12:29:42Z"
  },
  {
    "publicId": "IMG_6337_jd92uk",
    "folder": "",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 3275381,
    "createdAt": "2026-05-09T12:29:42Z"
  },
  {
    "publicId": "IMG_4841_ngrwt9",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1800396,
    "createdAt": "2026-05-09T12:29:49Z"
  },
  {
    "publicId": "1e4431d9-ec4f-4afb-96a9-c20b5e993436_b7nzmf",
    "folder": "",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 107881,
    "createdAt": "2026-05-09T12:43:13Z"
  },
  {
    "publicId": "0c7ec22a-5974-4e16-8540-77a093ce215f_eqp861",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 231512,
    "createdAt": "2026-05-09T12:43:14Z"
  },
  {
    "publicId": "524ddbb0-f76c-42e8-9acd-db90f66b3808_lq7wlr",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 218366,
    "createdAt": "2026-05-09T12:43:14Z"
  },
  {
    "publicId": "2f851225-210d-4512-ad14-dd59ebebea1f_rhua5t",
    "folder": "Generic",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 222113,
    "createdAt": "2026-05-09T12:43:15Z"
  },
  {
    "publicId": "2fc364aa-fe9c-4892-9c61-ab9b0cad67ec_jfzvsl",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 211233,
    "createdAt": "2026-05-09T12:43:15Z"
  },
  {
    "publicId": "22c1c739-8d5b-460f-8dce-b5a222a6ccc2_i8bpt9",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 253506,
    "createdAt": "2026-05-09T12:43:16Z"
  },
  {
    "publicId": "4aae4237-9e06-4292-a272-98127013aaed_sbyt7w",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 199985,
    "createdAt": "2026-05-09T12:43:16Z"
  },
  {
    "publicId": "3032b368-0702-416a-861c-42e1012770ff_x3yxis",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 1009640,
    "createdAt": "2026-05-09T12:43:17Z"
  },
  {
    "publicId": "45e7db4f-0f0e-41bc-a592-626be1115118_g322tw",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 190254,
    "createdAt": "2026-05-09T12:43:17Z"
  },
  {
    "publicId": "91b3d4f0-0942-450d-8484-3728c40f3893_wbkeah",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 218870,
    "createdAt": "2026-05-09T12:43:17Z"
  },
  {
    "publicId": "43fb09b1-9d04-410a-87c0-44a926eafbe2_kbxxxw",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 1054721,
    "createdAt": "2026-05-09T12:43:18Z"
  },
  {
    "publicId": "26a95e53-c04f-44e4-8f7f-a5a327ef41aa_m8ukjp",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 805267,
    "createdAt": "2026-05-09T12:43:18Z"
  },
  {
    "publicId": "176fe8a5-df89-42f8-9519-6a085132d3b6_icx0td",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 206391,
    "createdAt": "2026-05-09T12:43:18Z"
  },
  {
    "publicId": "133d5467-d575-4aba-a2df-7791a9812adc_aj3hao",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 200688,
    "createdAt": "2026-05-09T12:43:18Z"
  },
  {
    "publicId": "60cfe784-81cf-4a4e-b76e-7fd3cdbe9da7_usadgo",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 824400,
    "createdAt": "2026-05-09T12:43:19Z"
  },
  {
    "publicId": "725c36bf-b1ee-46f4-a9b5-f19ea53c10dc_c5vo6m",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1301117,
    "createdAt": "2026-05-09T12:43:20Z"
  },
  {
    "publicId": "85131a51-d94f-4f48-8027-1d7a953c5c8f_grb8hf",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1372990,
    "createdAt": "2026-05-09T12:43:20Z"
  },
  {
    "publicId": "70c57e70-855e-447c-9c2b-bc2d0aba082d_d4qelg",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1282114,
    "createdAt": "2026-05-09T12:43:21Z"
  },
  {
    "publicId": "3eb1e8d4-1e7c-4b11-a39b-c92d4a272775_n39fcl",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1465635,
    "createdAt": "2026-05-09T12:43:21Z"
  },
  {
    "publicId": "53e91b5d-726c-4ae9-bb43-0fd050d0bb5a_vawji7",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1463490,
    "createdAt": "2026-05-09T12:43:23Z"
  },
  {
    "publicId": "719ba0d7-2ea2-4862-bf45-4c3ef4fa07fd_ezrawv",
    "folder": "Coldplay",
    "type": "image",
    "width": 3120,
    "height": 4160,
    "bytes": 2417788,
    "createdAt": "2026-05-09T12:43:24Z"
  },
  {
    "publicId": "0c7ec22a-5974-4e16-8540-77a093ce215f_ipznma",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 231512,
    "createdAt": "2026-05-09T12:43:43Z"
  },
  {
    "publicId": "2fc364aa-fe9c-4892-9c61-ab9b0cad67ec_nxsatd",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 211233,
    "createdAt": "2026-05-09T12:43:44Z"
  },
  {
    "publicId": "2f851225-210d-4512-ad14-dd59ebebea1f_mvisxp",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 222113,
    "createdAt": "2026-05-09T12:43:44Z"
  },
  {
    "publicId": "1e4431d9-ec4f-4afb-96a9-c20b5e993436_kk8nvt",
    "folder": "",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 107881,
    "createdAt": "2026-05-09T12:43:44Z"
  },
  {
    "publicId": "4a9c3218-d2bf-4b2e-8920-f1a58603146e_v6lgb9",
    "folder": "In Her Element",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 148796,
    "createdAt": "2026-05-09T12:43:45Z"
  },
  {
    "publicId": "9a9819b7-f488-42a1-b8d6-87c4d1e89f73_nd01ez",
    "folder": "In Her Element",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 177915,
    "createdAt": "2026-05-09T12:43:45Z"
  },
  {
    "publicId": "3eb1e8d4-1e7c-4b11-a39b-c92d4a272775_bgknp2",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1465635,
    "createdAt": "2026-05-09T12:43:45Z"
  },
  {
    "publicId": "4aae4237-9e06-4292-a272-98127013aaed_w2frlx",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 199985,
    "createdAt": "2026-05-09T12:43:45Z"
  },
  {
    "publicId": "21a5fd09-1487-43ec-9b26-454f0ac292ae_bt4xi1",
    "folder": "Coldplay",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1353139,
    "createdAt": "2026-05-09T12:43:46Z"
  },
  {
    "publicId": "26a95e53-c04f-44e4-8f7f-a5a327ef41aa_w5u6hc",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 805267,
    "createdAt": "2026-05-09T12:43:46Z"
  },
  {
    "publicId": "6ef27684-8ae0-4b47-a956-92fbd68c781f_vmfrqf",
    "folder": "In Her Element",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 89863,
    "createdAt": "2026-05-09T12:43:46Z"
  },
  {
    "publicId": "9da79b54-46d5-4436-8660-30cbb1a0d45b_lfafy5",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1600,
    "height": 1200,
    "bytes": 266388,
    "createdAt": "2026-05-09T12:43:46Z"
  },
  {
    "publicId": "43fb09b1-9d04-410a-87c0-44a926eafbe2_antyyh",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 1054721,
    "createdAt": "2026-05-09T12:43:47Z"
  },
  {
    "publicId": "45e7db4f-0f0e-41bc-a592-626be1115118_dq1udj",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 190254,
    "createdAt": "2026-05-09T12:43:47Z"
  },
  {
    "publicId": "38a423d9-d3f4-47e3-a1dc-1517c4688e83_ivobna",
    "folder": "Coldplay",
    "type": "image",
    "width": 2252,
    "height": 4000,
    "bytes": 1207346,
    "createdAt": "2026-05-09T12:43:47Z"
  },
  {
    "publicId": "22c1c739-8d5b-460f-8dce-b5a222a6ccc2_ukhdxn",
    "folder": "Generic",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 253506,
    "createdAt": "2026-05-09T12:43:47Z"
  },
  {
    "publicId": "43bdf709-5b10-479c-a631-e9960c06af7e_pvtc1t",
    "folder": "Coldplay",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 1582658,
    "createdAt": "2026-05-09T12:43:47Z"
  },
  {
    "publicId": "50bdb122-582e-483f-b848-78498dbd2446_thx0rw",
    "folder": "Where it All Began",
    "type": "image",
    "width": 3000,
    "height": 4000,
    "bytes": 1091674,
    "createdAt": "2026-05-09T12:43:49Z"
  },
  {
    "publicId": "70c57e70-855e-447c-9c2b-bc2d0aba082d_hbvddm",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1282114,
    "createdAt": "2026-05-09T12:43:49Z"
  },
  {
    "publicId": "60cfe784-81cf-4a4e-b76e-7fd3cdbe9da7_w1wrgi",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 824400,
    "createdAt": "2026-05-09T12:43:49Z"
  },
  {
    "publicId": "91b3d4f0-0942-450d-8484-3728c40f3893_cemazr",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 218870,
    "createdAt": "2026-05-09T12:43:49Z"
  },
  {
    "publicId": "58f5e5fc-1f77-4be1-9923-8f45a1db94e7_hbsbuj",
    "folder": "Coldplay",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 1600633,
    "createdAt": "2026-05-09T12:43:49Z"
  },
  {
    "publicId": "129f7d0d-5ebd-4d38-86d2-1eb0696e72bc_poxjgc",
    "folder": "Coldplay",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1575471,
    "createdAt": "2026-05-09T12:43:50Z"
  },
  {
    "publicId": "176fe8a5-df89-42f8-9519-6a085132d3b6_gg0e3e",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 206391,
    "createdAt": "2026-05-09T12:43:50Z"
  },
  {
    "publicId": "133d5467-d575-4aba-a2df-7791a9812adc_usqmw3",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 200688,
    "createdAt": "2026-05-09T12:43:50Z"
  },
  {
    "publicId": "115c4594-d073-4672-9d51-624791a6795d_gxdpg6",
    "folder": "In Her Element",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 75787,
    "createdAt": "2026-05-09T12:43:50Z"
  },
  {
    "publicId": "299d471f-1559-4d86-a8ae-9b1d5829df45_fzvzpk",
    "folder": "",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1032505,
    "createdAt": "2026-05-09T12:43:51Z"
  },
  {
    "publicId": "524ddbb0-f76c-42e8-9acd-db90f66b3808_omyqhl",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 218366,
    "createdAt": "2026-05-09T12:43:51Z"
  },
  {
    "publicId": "258a90b9-2e8e-45d9-8efb-3e5eea930cbe_evr3nl",
    "folder": "Coldplay",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1010539,
    "createdAt": "2026-05-09T12:43:51Z"
  },
  {
    "publicId": "3032b368-0702-416a-861c-42e1012770ff_x7njkf",
    "folder": "",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 1009640,
    "createdAt": "2026-05-09T12:43:52Z"
  },
  {
    "publicId": "828c5f7a-c395-403e-b18c-b55ae9338221_owsn9z",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1200,
    "height": 1600,
    "bytes": 475303,
    "createdAt": "2026-05-09T12:43:52Z"
  },
  {
    "publicId": "9900d49f-5c43-4fdc-b53f-6379bcd52572_uwe9hu",
    "folder": "Where it All Began",
    "type": "image",
    "width": 3000,
    "height": 4000,
    "bytes": 1425704,
    "createdAt": "2026-05-09T12:43:53Z"
  },
  {
    "publicId": "8612be79-646a-4126-9fda-e86aa0f39c8a_x83ooi",
    "folder": "Coldplay",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 1618107,
    "createdAt": "2026-05-09T12:43:53Z"
  },
  {
    "publicId": "a0838c88-9ef6-4c2b-ab44-26816f43dc1e_zulkve",
    "folder": "In Her Element",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 187240,
    "createdAt": "2026-05-09T12:43:54Z"
  },
  {
    "publicId": "a8a7f213-3c96-42d1-9b3e-ae2934a6eac9_kvkyiy",
    "folder": "In Her Element",
    "type": "image",
    "width": 1600,
    "height": 1200,
    "bytes": 137885,
    "createdAt": "2026-05-09T12:43:54Z"
  },
  {
    "publicId": "494399be-9da5-4aad-9d47-81d822bf1b64_jd9mxr",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1200,
    "height": 1600,
    "bytes": 288558,
    "createdAt": "2026-05-09T12:43:54Z"
  },
  {
    "publicId": "a5306fb9-f525-48e6-9d80-c01e3e29747a_oqrm0j",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 255063,
    "createdAt": "2026-05-09T12:43:55Z"
  },
  {
    "publicId": "a7675320-ddd7-425b-966d-fbc363900895_ducxw6",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 230006,
    "createdAt": "2026-05-09T12:43:55Z"
  },
  {
    "publicId": "b5146d1a-674d-4656-a6c6-1f93294a598b_jshefe",
    "folder": "In Her Element",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 109050,
    "createdAt": "2026-05-09T12:44:18Z"
  },
  {
    "publicId": "b79eb503-40bf-4b67-8f3d-ce81b14239ac_tktdbb",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 177656,
    "createdAt": "2026-05-09T12:44:18Z"
  },
  {
    "publicId": "adb67dd4-77a3-4bf3-9a19-e2646d154f16_tssegv",
    "folder": "Generic",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 197614,
    "createdAt": "2026-05-09T12:44:18Z"
  },
  {
    "publicId": "b467dfbf-b2be-4605-8541-7fe7a18609e6_nig4su",
    "folder": "Where it All Began",
    "type": "image",
    "width": 3000,
    "height": 4000,
    "bytes": 1081511,
    "createdAt": "2026-05-09T12:44:20Z"
  },
  {
    "publicId": "c6246b87-defb-4b08-8ba2-3e08576900f0_sjslmo",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 184860,
    "createdAt": "2026-05-09T12:44:21Z"
  },
  {
    "publicId": "B4A13E31-55CA-415D-B0C8-2CFC0025CC67_gwendu",
    "folder": "In Her Element",
    "type": "image",
    "width": 2160,
    "height": 3840,
    "bytes": 730338,
    "createdAt": "2026-05-09T12:44:22Z"
  },
  {
    "publicId": "adda38da-a19c-484c-9d00-f34f21a662f4_yoqjkq",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 223203,
    "createdAt": "2026-05-09T12:44:22Z"
  },
  {
    "publicId": "ca418172-a635-4b48-9e5b-b18e6b32e809_w1zcjw",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1200,
    "height": 1600,
    "bytes": 203921,
    "createdAt": "2026-05-09T12:44:23Z"
  },
  {
    "publicId": "c47efeba-b0ac-48b6-b7a1-18034e9f72ab_gndoc1",
    "folder": "Coldplay",
    "type": "video",
    "width": 1280,
    "height": 720,
    "bytes": 1433956,
    "createdAt": "2026-05-09T12:44:23Z"
  },
  {
    "publicId": "d8f439ef-cfc3-4355-a769-8672f3e9d527_ssjfyq",
    "folder": "",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 120609,
    "createdAt": "2026-05-09T12:44:25Z"
  },
  {
    "publicId": "d57a491e-88cc-46cb-a50d-c96c20721012_rqebqz",
    "folder": "Coldplay",
    "type": "image",
    "width": 1818,
    "height": 4029,
    "bytes": 1116713,
    "createdAt": "2026-05-09T12:44:33Z"
  },
  {
    "publicId": "d63dbea5-919a-45c2-9c30-babd21744a54_jj3dpp",
    "folder": "In Her Element",
    "type": "video",
    "width": 464,
    "height": 832,
    "bytes": 4005439,
    "createdAt": "2026-05-09T12:44:34Z"
  },
  {
    "publicId": "db48ef7d-694c-4762-ae13-082a06e265e0_dol3fl",
    "folder": "In Her Element",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 111688,
    "createdAt": "2026-05-09T12:44:35Z"
  },
  {
    "publicId": "d09799a6-0abb-433e-8bf9-7ad35df63984_tzhtrv",
    "folder": "Coldplay",
    "type": "image",
    "width": 3120,
    "height": 4160,
    "bytes": 2620072,
    "createdAt": "2026-05-09T12:44:35Z"
  },
  {
    "publicId": "db2813c9-11be-4ca9-92ef-c082b288f645_nutqjx",
    "folder": "Coldplay",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 905994,
    "createdAt": "2026-05-09T12:45:15Z"
  },
  {
    "publicId": "e150e941-a2e1-4c8e-9362-369155fd791c_gbc2ul",
    "folder": "Generic",
    "type": "image",
    "width": 2295,
    "height": 4080,
    "bytes": 753761,
    "createdAt": "2026-05-09T12:45:18Z"
  },
  {
    "publicId": "ec3991f3-d6c4-471d-94d2-70eafc5b6244_gkyil7",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 239189,
    "createdAt": "2026-05-09T12:45:19Z"
  },
  {
    "publicId": "ef385bfd-c044-4359-a6a8-635487d1e71d_e09ben",
    "folder": "",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 125987,
    "createdAt": "2026-05-09T12:45:20Z"
  },
  {
    "publicId": "f0a70dae-a9ab-48d6-9856-0388eadc52f1_hgfqr4",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 194958,
    "createdAt": "2026-05-09T12:45:21Z"
  },
  {
    "publicId": "f3f5e3f3-7d6c-4320-a36e-9de2f2fb6a7c_y1ovzp",
    "folder": "Generic",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 180040,
    "createdAt": "2026-05-09T12:45:22Z"
  },
  {
    "publicId": "f7fdf738-c014-477f-9ac0-e93596fd0172_ip31nt",
    "folder": "",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 237185,
    "createdAt": "2026-05-09T12:45:24Z"
  },
  {
    "publicId": "f6a790aa-f1f8-4461-a036-963dcb187446_nhfxzo",
    "folder": "In Her Element",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 135306,
    "createdAt": "2026-05-09T12:45:24Z"
  },
  {
    "publicId": "BBC668C2-6527-43B0-9DF3-8B2E9275EF6C_vyvzre",
    "folder": "In Her Element",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 11844050,
    "createdAt": "2026-05-09T12:45:24Z"
  },
  {
    "publicId": "f181019c-7d11-41af-811a-7235576f4998_snfz6r",
    "folder": "",
    "type": "image",
    "width": 720,
    "height": 1280,
    "bytes": 123230,
    "createdAt": "2026-05-09T12:45:25Z"
  },
  {
    "publicId": "f812fc3a-ed9c-4b12-beec-1e103e8f5ab8_t5ownc",
    "folder": "Generic",
    "type": "image",
    "width": 960,
    "height": 1280,
    "bytes": 234209,
    "createdAt": "2026-05-09T12:45:25Z"
  },
  {
    "publicId": "fb4fd44f-7fa8-4afa-8032-f4f861f724a6_kbzyeu",
    "folder": "",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 189716,
    "createdAt": "2026-05-09T12:45:26Z"
  },
  {
    "publicId": "ff2d39da-63da-46b9-9e63-d39a52863f3a_syr6d2",
    "folder": "Coldplay",
    "type": "image",
    "width": 3120,
    "height": 4160,
    "bytes": 2138560,
    "createdAt": "2026-05-09T12:45:27Z"
  },
  {
    "publicId": "fa112b4e-3f9e-494b-95bc-010a6b2022c5_vprsm2",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 987241,
    "createdAt": "2026-05-09T12:45:27Z"
  },
  {
    "publicId": "IMG_0055_yxmfnw",
    "folder": "",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 3131054,
    "createdAt": "2026-05-09T12:45:29Z"
  },
  {
    "publicId": "IMG_0056_d1g0ws",
    "folder": "",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 2747614,
    "createdAt": "2026-05-09T12:45:31Z"
  },
  {
    "publicId": "IMG_0061_uhqsxx",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1547320,
    "createdAt": "2026-05-09T12:45:32Z"
  },
  {
    "publicId": "IMG_0088_tvagj3",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1126373,
    "createdAt": "2026-05-09T12:45:33Z"
  },
  {
    "publicId": "IMG_0062_f25tad",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1520845,
    "createdAt": "2026-05-09T12:45:33Z"
  },
  {
    "publicId": "IMG_0177_bquwrg",
    "folder": "Where it All Began",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 2691393,
    "createdAt": "2026-05-09T12:45:35Z"
  },
  {
    "publicId": "IMG_2265_bzig5b",
    "folder": "",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1628220,
    "createdAt": "2026-05-09T12:45:36Z"
  },
  {
    "publicId": "IMG_0181_bbskrl",
    "folder": "In Her Element",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1240261,
    "createdAt": "2026-05-09T12:45:36Z"
  },
  {
    "publicId": "IMG_2268_dliggy",
    "folder": "",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1831518,
    "createdAt": "2026-05-09T12:45:37Z"
  },
  {
    "publicId": "IMG_2266_uxfkko",
    "folder": "",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1711598,
    "createdAt": "2026-05-09T12:45:37Z"
  },
  {
    "publicId": "IMG_2267_d5e31d",
    "folder": "Generic",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1850083,
    "createdAt": "2026-05-09T12:45:37Z"
  },
  {
    "publicId": "IMG_2858_cdcg1b",
    "folder": "",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 3097315,
    "createdAt": "2026-05-09T12:45:38Z"
  },
  {
    "publicId": "IMG_2881_zxxobt",
    "folder": "",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 3713681,
    "createdAt": "2026-05-09T12:45:38Z"
  },
  {
    "publicId": "IMG_2857_qlrqwe",
    "folder": "Generic",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 3271141,
    "createdAt": "2026-05-09T12:45:38Z"
  },
  {
    "publicId": "IMG_2882_ncnguk",
    "folder": "Generic",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 3828960,
    "createdAt": "2026-05-09T12:45:40Z"
  },
  {
    "publicId": "IMG_4910_y0epvh",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 889196,
    "createdAt": "2026-05-09T12:45:41Z"
  },
  {
    "publicId": "IMG_4924_rnvkyc",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1264805,
    "createdAt": "2026-05-09T12:45:44Z"
  },
  {
    "publicId": "IMG_4959_pvjur9",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 2880009,
    "createdAt": "2026-05-09T12:45:45Z"
  },
  {
    "publicId": "IMG_4916_x4nwap",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1948382,
    "createdAt": "2026-05-09T12:45:45Z"
  },
  {
    "publicId": "IMG_4961_izg2ij",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 3131171,
    "createdAt": "2026-05-09T12:45:46Z"
  },
  {
    "publicId": "IMG_6193_nkllnx",
    "folder": "In Her Element",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 490260,
    "createdAt": "2026-05-09T12:45:47Z"
  },
  {
    "publicId": "IMG_4964_hdjrbr",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 2990552,
    "createdAt": "2026-05-09T12:45:47Z"
  },
  {
    "publicId": "IMG_6192_ibsnjj",
    "folder": "In Her Element",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 466755,
    "createdAt": "2026-05-09T12:45:47Z"
  },
  {
    "publicId": "IMG_6347_gdmwhi",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1373245,
    "createdAt": "2026-05-09T12:45:48Z"
  },
  {
    "publicId": "IMG_6346_sqlrx3",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1315391,
    "createdAt": "2026-05-09T12:45:48Z"
  },
  {
    "publicId": "IMG_6360_bpsh1l",
    "folder": "Trips",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 2844963,
    "createdAt": "2026-05-09T12:45:49Z"
  },
  {
    "publicId": "IMG_6360_itfapk",
    "folder": "Trips",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 2659077,
    "createdAt": "2026-05-09T12:45:49Z"
  },
  {
    "publicId": "IMG_6416_zojomo",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1627612,
    "createdAt": "2026-05-09T12:45:51Z"
  },
  {
    "publicId": "IMG_6439_noxesm",
    "folder": "In Her Element",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 2561833,
    "createdAt": "2026-05-09T12:45:55Z"
  },
  {
    "publicId": "IMG_6488_dpjogf",
    "folder": "Trips",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 2729340,
    "createdAt": "2026-05-09T12:45:58Z"
  },
  {
    "publicId": "IMG_6589_smusg4",
    "folder": "In Her Element",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 322583,
    "createdAt": "2026-05-09T12:46:02Z"
  },
  {
    "publicId": "IMG_6594_nehnni",
    "folder": "Trips",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 1962568,
    "createdAt": "2026-05-09T12:46:04Z"
  },
  {
    "publicId": "IMG_6479_cmdflh",
    "folder": "Trips",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 3655219,
    "createdAt": "2026-05-09T12:46:06Z"
  },
  {
    "publicId": "IMG_6585_cz57hh",
    "folder": "Trips",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 5044520,
    "createdAt": "2026-05-09T12:46:07Z"
  },
  {
    "publicId": "IMG_6763_wvw3kv",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 3966902,
    "createdAt": "2026-05-09T12:46:07Z"
  },
  {
    "publicId": "IMG_6767_zjr5gb",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 3582115,
    "createdAt": "2026-05-09T12:46:09Z"
  },
  {
    "publicId": "IMG_6803_kypztp",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 2157938,
    "createdAt": "2026-05-09T12:46:10Z"
  },
  {
    "publicId": "IMG_6830_lfzzy8",
    "folder": "Trips",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 2332501,
    "createdAt": "2026-05-09T12:46:11Z"
  },
  {
    "publicId": "IMG_6870_vvveql",
    "folder": "In Her Element",
    "type": "image",
    "width": 4284,
    "height": 5712,
    "bytes": 3002751,
    "createdAt": "2026-05-09T12:46:12Z"
  },
  {
    "publicId": "IMG_6896_qld3il",
    "folder": "In Her Element",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1663820,
    "createdAt": "2026-05-09T12:46:12Z"
  },
  {
    "publicId": "IMG_6899_jerftg",
    "folder": "In Her Element",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1757520,
    "createdAt": "2026-05-09T12:46:13Z"
  },
  {
    "publicId": "IMG_6943_gnemfv",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1629759,
    "createdAt": "2026-05-09T12:46:14Z"
  },
  {
    "publicId": "IMG_6945_l3b7ga",
    "folder": "Trips",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1404376,
    "createdAt": "2026-05-09T12:46:15Z"
  },
  {
    "publicId": "IMG_7101_tt7eot",
    "folder": "Trips",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 2727542,
    "createdAt": "2026-05-09T12:46:16Z"
  },
  {
    "publicId": "IMG_7103_sx6q7e",
    "folder": "Trips",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 2693243,
    "createdAt": "2026-05-09T12:46:17Z"
  },
  {
    "publicId": "IMG_7145_tsbjrf",
    "folder": "Trips",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1676851,
    "createdAt": "2026-05-09T12:46:18Z"
  },
  {
    "publicId": "IMG_8244_fntm7w",
    "folder": "In Her Element",
    "type": "image",
    "width": 2316,
    "height": 3088,
    "bytes": 1901209,
    "createdAt": "2026-05-09T12:46:19Z"
  },
  {
    "publicId": "IMG_8422_yytiqf",
    "folder": "Where it All Began",
    "type": "image",
    "width": 1242,
    "height": 2208,
    "bytes": 361747,
    "createdAt": "2026-05-09T12:46:19Z"
  },
  {
    "publicId": "IMG_9346_vpjrkp",
    "folder": "Trips",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 2272884,
    "createdAt": "2026-05-09T12:46:21Z"
  },
  {
    "publicId": "IMG_9352_jnbe1g",
    "folder": "Trips",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 3032327,
    "createdAt": "2026-05-09T12:46:22Z"
  },
  {
    "publicId": "IMG_9349_hjcvoh",
    "folder": "Trips",
    "type": "image",
    "width": 4032,
    "height": 2268,
    "bytes": 1853751,
    "createdAt": "2026-05-09T12:46:22Z"
  },
  {
    "publicId": "IMG_9354_qf8cye",
    "folder": "Trips",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 2934699,
    "createdAt": "2026-05-09T12:46:24Z"
  },
  {
    "publicId": "IMG_9373_dl2dyz",
    "folder": "Trips",
    "type": "image",
    "width": 2268,
    "height": 4032,
    "bytes": 2153375,
    "createdAt": "2026-05-09T12:46:24Z"
  },
  {
    "publicId": "IMG_9382_v6jjfq",
    "folder": "Trips",
    "type": "image",
    "width": 1737,
    "height": 3088,
    "bytes": 1303376,
    "createdAt": "2026-05-09T12:46:25Z"
  },
  {
    "publicId": "IMG_2885_hzqkds",
    "folder": "In Her Element",
    "type": "video",
    "width": 2160,
    "height": 3840,
    "bytes": 29537790,
    "createdAt": "2026-05-09T12:46:29Z"
  },
  {
    "publicId": "IMG_6377_z4j207",
    "folder": "In Her Element",
    "type": "video",
    "width": 2160,
    "height": 3840,
    "bytes": 32239019,
    "createdAt": "2026-05-09T12:46:32Z"
  },
  {
    "publicId": "IMG_0052_ygwpeo",
    "folder": "In Her Element",
    "type": "video",
    "width": 1080,
    "height": 1920,
    "bytes": 70338792,
    "createdAt": "2026-05-09T12:46:39Z"
  },
  {
    "publicId": "dcc4eab7-e7fc-4fea-82cf-203779695b48_d70xzc",
    "folder": "Generic",
    "type": "image",
    "width": 900,
    "height": 1600,
    "bytes": 188431,
    "createdAt": "2026-05-09T12:46:44Z"
  },
  {
    "publicId": "d79a7a5b-8920-4d74-988b-8101c7592876_atnqtv",
    "folder": "Coldplay",
    "type": "image",
    "width": 3024,
    "height": 4032,
    "bytes": 1693949,
    "createdAt": "2026-05-09T12:46:44Z"
  },
  {
    "publicId": "db3ace7e-c7de-4829-a49e-e72a76143b0b_jrw3y2",
    "folder": "Coldplay",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 1703985,
    "createdAt": "2026-05-09T12:46:45Z"
  },
  {
    "publicId": "filtered-8551B2F1-CB64-4CDF-91EF-5443617B5178_xa5gjb",
    "folder": "In Her Element",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 8888401,
    "createdAt": "2026-05-09T13:19:54Z"
  },
  {
    "publicId": "175272e7-77af-4e84-82ad-7c72d0798621_iqq08e",
    "folder": "Coldplay",
    "type": "image",
    "width": 4032,
    "height": 3024,
    "bytes": 1402735,
    "createdAt": "2026-05-09T13:53:11Z"
  },
  {
    "publicId": "47088be6-a5f0-4646-92a6-584f6e5ad667_lxcavu",
    "folder": "Coldplay",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 2722637,
    "createdAt": "2026-05-09T13:53:40Z"
  },
  {
    "publicId": "891e606b-8cf4-4704-833b-6ad333807566_raoavh",
    "folder": "Coldplay",
    "type": "video",
    "width": 720,
    "height": 1280,
    "bytes": 9388110,
    "createdAt": "2026-05-09T13:53:45Z"
  }
];

export const cldByFolder: Record<string, CldAsset[]> = {
  "_root": [
    {
      "publicId": "sample",
      "folder": "",
      "type": "image",
      "width": 864,
      "height": 576,
      "bytes": 120253,
      "createdAt": "2026-05-09T07:50:19Z"
    },
    {
      "publicId": "cld-sample",
      "folder": "",
      "type": "image",
      "width": 1870,
      "height": 1250,
      "bytes": 476846,
      "createdAt": "2026-05-09T07:50:53Z"
    },
    {
      "publicId": "cld-sample-2",
      "folder": "",
      "type": "image",
      "width": 1870,
      "height": 1250,
      "bytes": 592235,
      "createdAt": "2026-05-09T07:50:53Z"
    },
    {
      "publicId": "cld-sample-4",
      "folder": "",
      "type": "image",
      "width": 1870,
      "height": 1250,
      "bytes": 818600,
      "createdAt": "2026-05-09T07:50:54Z"
    },
    {
      "publicId": "cld-sample-3",
      "folder": "",
      "type": "image",
      "width": 1870,
      "height": 1250,
      "bytes": 905834,
      "createdAt": "2026-05-09T07:50:54Z"
    },
    {
      "publicId": "cld-sample-5",
      "folder": "",
      "type": "image",
      "width": 1870,
      "height": 1250,
      "bytes": 379132,
      "createdAt": "2026-05-09T07:50:55Z"
    },
    {
      "publicId": "main-sample",
      "folder": "",
      "type": "image",
      "width": 1248,
      "height": 832,
      "bytes": 1868954,
      "createdAt": "2026-05-09T07:50:55Z"
    },
    {
      "publicId": "IMG_6337_jd92uk",
      "folder": "",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 3275381,
      "createdAt": "2026-05-09T12:29:42Z"
    },
    {
      "publicId": "1e4431d9-ec4f-4afb-96a9-c20b5e993436_b7nzmf",
      "folder": "",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 107881,
      "createdAt": "2026-05-09T12:43:13Z"
    },
    {
      "publicId": "0c7ec22a-5974-4e16-8540-77a093ce215f_eqp861",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 231512,
      "createdAt": "2026-05-09T12:43:14Z"
    },
    {
      "publicId": "524ddbb0-f76c-42e8-9acd-db90f66b3808_lq7wlr",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 218366,
      "createdAt": "2026-05-09T12:43:14Z"
    },
    {
      "publicId": "2fc364aa-fe9c-4892-9c61-ab9b0cad67ec_jfzvsl",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 211233,
      "createdAt": "2026-05-09T12:43:15Z"
    },
    {
      "publicId": "22c1c739-8d5b-460f-8dce-b5a222a6ccc2_i8bpt9",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 253506,
      "createdAt": "2026-05-09T12:43:16Z"
    },
    {
      "publicId": "4aae4237-9e06-4292-a272-98127013aaed_sbyt7w",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 199985,
      "createdAt": "2026-05-09T12:43:16Z"
    },
    {
      "publicId": "3032b368-0702-416a-861c-42e1012770ff_x3yxis",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 1009640,
      "createdAt": "2026-05-09T12:43:17Z"
    },
    {
      "publicId": "45e7db4f-0f0e-41bc-a592-626be1115118_g322tw",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 190254,
      "createdAt": "2026-05-09T12:43:17Z"
    },
    {
      "publicId": "91b3d4f0-0942-450d-8484-3728c40f3893_wbkeah",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 218870,
      "createdAt": "2026-05-09T12:43:17Z"
    },
    {
      "publicId": "43fb09b1-9d04-410a-87c0-44a926eafbe2_kbxxxw",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 1054721,
      "createdAt": "2026-05-09T12:43:18Z"
    },
    {
      "publicId": "26a95e53-c04f-44e4-8f7f-a5a327ef41aa_m8ukjp",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 805267,
      "createdAt": "2026-05-09T12:43:18Z"
    },
    {
      "publicId": "176fe8a5-df89-42f8-9519-6a085132d3b6_icx0td",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 206391,
      "createdAt": "2026-05-09T12:43:18Z"
    },
    {
      "publicId": "133d5467-d575-4aba-a2df-7791a9812adc_aj3hao",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 200688,
      "createdAt": "2026-05-09T12:43:18Z"
    },
    {
      "publicId": "60cfe784-81cf-4a4e-b76e-7fd3cdbe9da7_usadgo",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 824400,
      "createdAt": "2026-05-09T12:43:19Z"
    },
    {
      "publicId": "0c7ec22a-5974-4e16-8540-77a093ce215f_ipznma",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 231512,
      "createdAt": "2026-05-09T12:43:43Z"
    },
    {
      "publicId": "2fc364aa-fe9c-4892-9c61-ab9b0cad67ec_nxsatd",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 211233,
      "createdAt": "2026-05-09T12:43:44Z"
    },
    {
      "publicId": "2f851225-210d-4512-ad14-dd59ebebea1f_mvisxp",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 222113,
      "createdAt": "2026-05-09T12:43:44Z"
    },
    {
      "publicId": "1e4431d9-ec4f-4afb-96a9-c20b5e993436_kk8nvt",
      "folder": "",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 107881,
      "createdAt": "2026-05-09T12:43:44Z"
    },
    {
      "publicId": "4aae4237-9e06-4292-a272-98127013aaed_w2frlx",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 199985,
      "createdAt": "2026-05-09T12:43:45Z"
    },
    {
      "publicId": "26a95e53-c04f-44e4-8f7f-a5a327ef41aa_w5u6hc",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 805267,
      "createdAt": "2026-05-09T12:43:46Z"
    },
    {
      "publicId": "43fb09b1-9d04-410a-87c0-44a926eafbe2_antyyh",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 1054721,
      "createdAt": "2026-05-09T12:43:47Z"
    },
    {
      "publicId": "45e7db4f-0f0e-41bc-a592-626be1115118_dq1udj",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 190254,
      "createdAt": "2026-05-09T12:43:47Z"
    },
    {
      "publicId": "60cfe784-81cf-4a4e-b76e-7fd3cdbe9da7_w1wrgi",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 824400,
      "createdAt": "2026-05-09T12:43:49Z"
    },
    {
      "publicId": "91b3d4f0-0942-450d-8484-3728c40f3893_cemazr",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 218870,
      "createdAt": "2026-05-09T12:43:49Z"
    },
    {
      "publicId": "176fe8a5-df89-42f8-9519-6a085132d3b6_gg0e3e",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 206391,
      "createdAt": "2026-05-09T12:43:50Z"
    },
    {
      "publicId": "133d5467-d575-4aba-a2df-7791a9812adc_usqmw3",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 200688,
      "createdAt": "2026-05-09T12:43:50Z"
    },
    {
      "publicId": "299d471f-1559-4d86-a8ae-9b1d5829df45_fzvzpk",
      "folder": "",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1032505,
      "createdAt": "2026-05-09T12:43:51Z"
    },
    {
      "publicId": "524ddbb0-f76c-42e8-9acd-db90f66b3808_omyqhl",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 218366,
      "createdAt": "2026-05-09T12:43:51Z"
    },
    {
      "publicId": "3032b368-0702-416a-861c-42e1012770ff_x7njkf",
      "folder": "",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 1009640,
      "createdAt": "2026-05-09T12:43:52Z"
    },
    {
      "publicId": "a5306fb9-f525-48e6-9d80-c01e3e29747a_oqrm0j",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 255063,
      "createdAt": "2026-05-09T12:43:55Z"
    },
    {
      "publicId": "a7675320-ddd7-425b-966d-fbc363900895_ducxw6",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 230006,
      "createdAt": "2026-05-09T12:43:55Z"
    },
    {
      "publicId": "b79eb503-40bf-4b67-8f3d-ce81b14239ac_tktdbb",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 177656,
      "createdAt": "2026-05-09T12:44:18Z"
    },
    {
      "publicId": "c6246b87-defb-4b08-8ba2-3e08576900f0_sjslmo",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 184860,
      "createdAt": "2026-05-09T12:44:21Z"
    },
    {
      "publicId": "adda38da-a19c-484c-9d00-f34f21a662f4_yoqjkq",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 223203,
      "createdAt": "2026-05-09T12:44:22Z"
    },
    {
      "publicId": "d8f439ef-cfc3-4355-a769-8672f3e9d527_ssjfyq",
      "folder": "",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 120609,
      "createdAt": "2026-05-09T12:44:25Z"
    },
    {
      "publicId": "ec3991f3-d6c4-471d-94d2-70eafc5b6244_gkyil7",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 239189,
      "createdAt": "2026-05-09T12:45:19Z"
    },
    {
      "publicId": "ef385bfd-c044-4359-a6a8-635487d1e71d_e09ben",
      "folder": "",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 125987,
      "createdAt": "2026-05-09T12:45:20Z"
    },
    {
      "publicId": "f0a70dae-a9ab-48d6-9856-0388eadc52f1_hgfqr4",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 194958,
      "createdAt": "2026-05-09T12:45:21Z"
    },
    {
      "publicId": "f7fdf738-c014-477f-9ac0-e93596fd0172_ip31nt",
      "folder": "",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 237185,
      "createdAt": "2026-05-09T12:45:24Z"
    },
    {
      "publicId": "f181019c-7d11-41af-811a-7235576f4998_snfz6r",
      "folder": "",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 123230,
      "createdAt": "2026-05-09T12:45:25Z"
    },
    {
      "publicId": "fb4fd44f-7fa8-4afa-8032-f4f861f724a6_kbzyeu",
      "folder": "",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 189716,
      "createdAt": "2026-05-09T12:45:26Z"
    },
    {
      "publicId": "IMG_0055_yxmfnw",
      "folder": "",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 3131054,
      "createdAt": "2026-05-09T12:45:29Z"
    },
    {
      "publicId": "IMG_0056_d1g0ws",
      "folder": "",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 2747614,
      "createdAt": "2026-05-09T12:45:31Z"
    },
    {
      "publicId": "IMG_2265_bzig5b",
      "folder": "",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1628220,
      "createdAt": "2026-05-09T12:45:36Z"
    },
    {
      "publicId": "IMG_2268_dliggy",
      "folder": "",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1831518,
      "createdAt": "2026-05-09T12:45:37Z"
    },
    {
      "publicId": "IMG_2266_uxfkko",
      "folder": "",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1711598,
      "createdAt": "2026-05-09T12:45:37Z"
    },
    {
      "publicId": "IMG_2858_cdcg1b",
      "folder": "",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 3097315,
      "createdAt": "2026-05-09T12:45:38Z"
    },
    {
      "publicId": "IMG_2881_zxxobt",
      "folder": "",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 3713681,
      "createdAt": "2026-05-09T12:45:38Z"
    }
  ],
  "samples": [
    {
      "publicId": "samples/cloudinary-logo-vector",
      "folder": "samples",
      "type": "image",
      "width": 1000,
      "height": 320,
      "bytes": 5961,
      "createdAt": "2026-05-09T07:50:28Z"
    },
    {
      "publicId": "samples/cloudinary-icon",
      "folder": "samples",
      "type": "image",
      "width": 1000,
      "height": 1000,
      "bytes": 57334,
      "createdAt": "2026-05-09T07:50:28Z"
    },
    {
      "publicId": "samples/sheep",
      "folder": "samples",
      "type": "image",
      "width": 1600,
      "height": 1067,
      "bytes": 269304,
      "createdAt": "2026-05-09T07:50:31Z"
    },
    {
      "publicId": "samples/bike",
      "folder": "samples",
      "type": "image",
      "width": 2000,
      "height": 1333,
      "bytes": 475687,
      "createdAt": "2026-05-09T07:50:32Z"
    },
    {
      "publicId": "samples/imagecon-group",
      "folder": "samples",
      "type": "image",
      "width": 2800,
      "height": 1867,
      "bytes": 1487070,
      "createdAt": "2026-05-09T07:50:35Z"
    },
    {
      "publicId": "samples/cloudinary-group",
      "folder": "samples",
      "type": "image",
      "width": 3000,
      "height": 1526,
      "bytes": 2856169,
      "createdAt": "2026-05-09T07:50:37Z"
    },
    {
      "publicId": "samples/sea-turtle",
      "folder": "samples",
      "type": "video",
      "width": 1920,
      "height": 1080,
      "bytes": 27932506,
      "createdAt": "2026-05-09T07:50:38Z"
    },
    {
      "publicId": "samples/elephants",
      "folder": "samples",
      "type": "video",
      "width": 1920,
      "height": 1080,
      "bytes": 38855178,
      "createdAt": "2026-05-09T07:50:38Z"
    },
    {
      "publicId": "samples/cld-sample-video",
      "folder": "samples",
      "type": "video",
      "width": 3840,
      "height": 2160,
      "bytes": 35988643,
      "createdAt": "2026-05-09T07:50:39Z"
    },
    {
      "publicId": "samples/dance-2",
      "folder": "samples",
      "type": "video",
      "width": 3840,
      "height": 2160,
      "bytes": 22373558,
      "createdAt": "2026-05-09T07:50:39Z"
    },
    {
      "publicId": "samples/two-ladies",
      "folder": "samples",
      "type": "image",
      "width": 1500,
      "height": 1200,
      "bytes": 211712,
      "createdAt": "2026-05-09T07:50:40Z"
    },
    {
      "publicId": "samples/shoe",
      "folder": "samples",
      "type": "image",
      "width": 1000,
      "height": 1140,
      "bytes": 72888,
      "createdAt": "2026-05-09T07:50:41Z"
    },
    {
      "publicId": "samples/balloons",
      "folder": "samples",
      "type": "image",
      "width": 1000,
      "height": 667,
      "bytes": 117237,
      "createdAt": "2026-05-09T07:50:42Z"
    },
    {
      "publicId": "samples/smile",
      "folder": "samples",
      "type": "image",
      "width": 1552,
      "height": 1000,
      "bytes": 657749,
      "createdAt": "2026-05-09T07:50:44Z"
    },
    {
      "publicId": "samples/breakfast",
      "folder": "samples",
      "type": "image",
      "width": 2447,
      "height": 2196,
      "bytes": 3024938,
      "createdAt": "2026-05-09T07:50:45Z"
    },
    {
      "publicId": "samples/man-on-a-escalator",
      "folder": "samples",
      "type": "image",
      "width": 1340,
      "height": 1340,
      "bytes": 563708,
      "createdAt": "2026-05-09T07:50:46Z"
    },
    {
      "publicId": "samples/look-up",
      "folder": "samples",
      "type": "image",
      "width": 900,
      "height": 900,
      "bytes": 414964,
      "createdAt": "2026-05-09T07:50:46Z"
    },
    {
      "publicId": "samples/man-on-a-street",
      "folder": "samples",
      "type": "image",
      "width": 1340,
      "height": 1340,
      "bytes": 564013,
      "createdAt": "2026-05-09T07:50:47Z"
    },
    {
      "publicId": "samples/outdoor-woman",
      "folder": "samples",
      "type": "image",
      "width": 640,
      "height": 963,
      "bytes": 93473,
      "createdAt": "2026-05-09T07:50:47Z"
    },
    {
      "publicId": "samples/chair",
      "folder": "samples",
      "type": "image",
      "width": 800,
      "height": 600,
      "bytes": 130488,
      "createdAt": "2026-05-09T07:50:48Z"
    },
    {
      "publicId": "samples/chair-and-coffee-table",
      "folder": "samples",
      "type": "image",
      "width": 1001,
      "height": 1500,
      "bytes": 64504,
      "createdAt": "2026-05-09T07:50:48Z"
    },
    {
      "publicId": "samples/dessert-on-a-plate",
      "folder": "samples",
      "type": "image",
      "width": 1200,
      "height": 1200,
      "bytes": 348717,
      "createdAt": "2026-05-09T07:50:49Z"
    },
    {
      "publicId": "samples/cup-on-a-table",
      "folder": "samples",
      "type": "image",
      "width": 2246,
      "height": 1500,
      "bytes": 134300,
      "createdAt": "2026-05-09T07:50:49Z"
    },
    {
      "publicId": "samples/man-portrait",
      "folder": "samples",
      "type": "image",
      "width": 1333,
      "height": 2000,
      "bytes": 505607,
      "createdAt": "2026-05-09T07:50:49Z"
    },
    {
      "publicId": "samples/upscale-face-1",
      "folder": "samples",
      "type": "image",
      "width": 233,
      "height": 233,
      "bytes": 18110,
      "createdAt": "2026-05-09T07:50:50Z"
    },
    {
      "publicId": "samples/coffee",
      "folder": "samples",
      "type": "image",
      "width": 1920,
      "height": 1280,
      "bytes": 165287,
      "createdAt": "2026-05-09T07:50:50Z"
    },
    {
      "publicId": "samples/woman-on-a-football-field",
      "folder": "samples",
      "type": "image",
      "width": 1200,
      "height": 1350,
      "bytes": 416598,
      "createdAt": "2026-05-09T07:50:51Z"
    },
    {
      "publicId": "samples/radial",
      "folder": "samples",
      "type": "image",
      "width": 950,
      "height": 640,
      "bytes": 4503,
      "createdAt": "2026-05-09T07:50:51Z"
    },
    {
      "publicId": "samples/canvas",
      "folder": "samples",
      "type": "image",
      "width": 600,
      "height": 388,
      "bytes": 61928,
      "createdAt": "2026-05-09T07:50:51Z"
    },
    {
      "publicId": "samples/logo",
      "folder": "samples",
      "type": "image",
      "width": 480,
      "height": 314,
      "bytes": 10897,
      "createdAt": "2026-05-09T07:50:51Z"
    },
    {
      "publicId": "samples/paper",
      "folder": "samples",
      "type": "image",
      "width": 1024,
      "height": 1024,
      "bytes": 1440561,
      "createdAt": "2026-05-09T07:50:52Z"
    },
    {
      "publicId": "samples/zoom",
      "folder": "samples",
      "type": "image",
      "width": 484,
      "height": 324,
      "bytes": 2863,
      "createdAt": "2026-05-09T07:50:52Z"
    },
    {
      "publicId": "samples/waves",
      "folder": "samples",
      "type": "image",
      "width": 1024,
      "height": 1024,
      "bytes": 1563444,
      "createdAt": "2026-05-09T07:50:53Z"
    },
    {
      "publicId": "samples/radial_02",
      "folder": "samples",
      "type": "image",
      "width": 427,
      "height": 271,
      "bytes": 123165,
      "createdAt": "2026-05-09T07:50:53Z"
    }
  ],
  "samples/food": [
    {
      "publicId": "samples/food/dessert",
      "folder": "samples/food",
      "type": "image",
      "width": 1220,
      "height": 813,
      "bytes": 125888,
      "createdAt": "2026-05-09T07:50:28Z"
    },
    {
      "publicId": "samples/food/pot-mussels",
      "folder": "samples/food",
      "type": "image",
      "width": 1220,
      "height": 818,
      "bytes": 191852,
      "createdAt": "2026-05-09T07:50:30Z"
    },
    {
      "publicId": "samples/food/fish-vegetables",
      "folder": "samples/food",
      "type": "image",
      "width": 1220,
      "height": 813,
      "bytes": 169013,
      "createdAt": "2026-05-09T07:50:30Z"
    },
    {
      "publicId": "samples/food/spices",
      "folder": "samples/food",
      "type": "image",
      "width": 2000,
      "height": 2000,
      "bytes": 2129950,
      "createdAt": "2026-05-09T07:50:36Z"
    }
  ],
  "samples/ecommerce": [
    {
      "publicId": "samples/ecommerce/analog-classic",
      "folder": "samples/ecommerce",
      "type": "image",
      "width": 1280,
      "height": 853,
      "bytes": 72558,
      "createdAt": "2026-05-09T07:50:28Z"
    },
    {
      "publicId": "samples/ecommerce/shoes",
      "folder": "samples/ecommerce",
      "type": "image",
      "width": 587,
      "height": 507,
      "bytes": 393265,
      "createdAt": "2026-05-09T07:50:32Z"
    },
    {
      "publicId": "samples/ecommerce/car-interior-design",
      "folder": "samples/ecommerce",
      "type": "image",
      "width": 2000,
      "height": 2667,
      "bytes": 1254103,
      "createdAt": "2026-05-09T07:50:34Z"
    },
    {
      "publicId": "samples/ecommerce/accessories-bag",
      "folder": "samples/ecommerce",
      "type": "image",
      "width": 3000,
      "height": 2000,
      "bytes": 1459256,
      "createdAt": "2026-05-09T07:50:35Z"
    },
    {
      "publicId": "samples/ecommerce/leather-bag-gray",
      "folder": "samples/ecommerce",
      "type": "image",
      "width": 2385,
      "height": 1590,
      "bytes": 1323582,
      "createdAt": "2026-05-09T07:50:36Z"
    }
  ],
  "samples/animals": [
    {
      "publicId": "samples/animals/cat",
      "folder": "samples/animals",
      "type": "image",
      "width": 768,
      "height": 1024,
      "bytes": 92690,
      "createdAt": "2026-05-09T07:50:29Z"
    },
    {
      "publicId": "samples/animals/reindeer",
      "folder": "samples/animals",
      "type": "image",
      "width": 1220,
      "height": 813,
      "bytes": 161150,
      "createdAt": "2026-05-09T07:50:30Z"
    },
    {
      "publicId": "samples/animals/three-dogs",
      "folder": "samples/animals",
      "type": "image",
      "width": 2700,
      "height": 1800,
      "bytes": 854929,
      "createdAt": "2026-05-09T07:50:34Z"
    },
    {
      "publicId": "samples/animals/kitten-playing",
      "folder": "samples/animals",
      "type": "image",
      "width": 320,
      "height": 180,
      "bytes": 6620002,
      "createdAt": "2026-05-09T07:50:38Z"
    }
  ],
  "samples/landscapes": [
    {
      "publicId": "samples/landscapes/girl-urban-view",
      "folder": "samples/landscapes",
      "type": "image",
      "width": 2048,
      "height": 1252,
      "bytes": 372778,
      "createdAt": "2026-05-09T07:50:31Z"
    },
    {
      "publicId": "samples/landscapes/beach-boat",
      "folder": "samples/landscapes",
      "type": "image",
      "width": 2600,
      "height": 1950,
      "bytes": 1235823,
      "createdAt": "2026-05-09T07:50:34Z"
    },
    {
      "publicId": "samples/landscapes/architecture-signs",
      "folder": "samples/landscapes",
      "type": "image",
      "width": 3000,
      "height": 2000,
      "bytes": 945255,
      "createdAt": "2026-05-09T07:50:34Z"
    },
    {
      "publicId": "samples/landscapes/nature-mountains",
      "folder": "samples/landscapes",
      "type": "image",
      "width": 3000,
      "height": 2000,
      "bytes": 3171453,
      "createdAt": "2026-05-09T07:50:36Z"
    },
    {
      "publicId": "samples/landscapes/landscape-panorama",
      "folder": "samples/landscapes",
      "type": "image",
      "width": 10906,
      "height": 2349,
      "bytes": 7858062,
      "createdAt": "2026-05-09T07:50:37Z"
    }
  ],
  "samples/people": [
    {
      "publicId": "samples/people/kitchen-bar",
      "folder": "samples/people",
      "type": "image",
      "width": 1220,
      "height": 813,
      "bytes": 154151,
      "createdAt": "2026-05-09T07:50:31Z"
    },
    {
      "publicId": "samples/people/smiling-man",
      "folder": "samples/people",
      "type": "image",
      "width": 849,
      "height": 565,
      "bytes": 338794,
      "createdAt": "2026-05-09T07:50:32Z"
    },
    {
      "publicId": "samples/people/boy-snow-hoodie",
      "folder": "samples/people",
      "type": "image",
      "width": 1777,
      "height": 1332,
      "bytes": 581238,
      "createdAt": "2026-05-09T07:50:32Z"
    },
    {
      "publicId": "samples/people/jazz",
      "folder": "samples/people",
      "type": "image",
      "width": 3000,
      "height": 1993,
      "bytes": 695548,
      "createdAt": "2026-05-09T07:50:33Z"
    },
    {
      "publicId": "samples/people/bicycle",
      "folder": "samples/people",
      "type": "image",
      "width": 2889,
      "height": 1926,
      "bytes": 1130015,
      "createdAt": "2026-05-09T07:50:34Z"
    }
  ],
  "Trips": [
    {
      "publicId": "IMG_6339_tn4m30",
      "folder": "Trips",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 391867,
      "createdAt": "2026-05-09T12:28:47Z"
    },
    {
      "publicId": "IMG_6349_umlt22",
      "folder": "Trips",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 420869,
      "createdAt": "2026-05-09T12:28:59Z"
    },
    {
      "publicId": "IMG_4839_jrao72",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1987418,
      "createdAt": "2026-05-09T12:29:31Z"
    },
    {
      "publicId": "IMG_6350_hzvbng",
      "folder": "Trips",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 426834,
      "createdAt": "2026-05-09T12:29:34Z"
    },
    {
      "publicId": "IMG_4841_ngrwt9",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1800396,
      "createdAt": "2026-05-09T12:29:49Z"
    },
    {
      "publicId": "IMG_4910_y0epvh",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 889196,
      "createdAt": "2026-05-09T12:45:41Z"
    },
    {
      "publicId": "IMG_4924_rnvkyc",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1264805,
      "createdAt": "2026-05-09T12:45:44Z"
    },
    {
      "publicId": "IMG_4959_pvjur9",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 2880009,
      "createdAt": "2026-05-09T12:45:45Z"
    },
    {
      "publicId": "IMG_4916_x4nwap",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1948382,
      "createdAt": "2026-05-09T12:45:45Z"
    },
    {
      "publicId": "IMG_4961_izg2ij",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 3131171,
      "createdAt": "2026-05-09T12:45:46Z"
    },
    {
      "publicId": "IMG_4964_hdjrbr",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 2990552,
      "createdAt": "2026-05-09T12:45:47Z"
    },
    {
      "publicId": "IMG_6347_gdmwhi",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1373245,
      "createdAt": "2026-05-09T12:45:48Z"
    },
    {
      "publicId": "IMG_6346_sqlrx3",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1315391,
      "createdAt": "2026-05-09T12:45:48Z"
    },
    {
      "publicId": "IMG_6360_bpsh1l",
      "folder": "Trips",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 2844963,
      "createdAt": "2026-05-09T12:45:49Z"
    },
    {
      "publicId": "IMG_6360_itfapk",
      "folder": "Trips",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 2659077,
      "createdAt": "2026-05-09T12:45:49Z"
    },
    {
      "publicId": "IMG_6416_zojomo",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1627612,
      "createdAt": "2026-05-09T12:45:51Z"
    },
    {
      "publicId": "IMG_6488_dpjogf",
      "folder": "Trips",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 2729340,
      "createdAt": "2026-05-09T12:45:58Z"
    },
    {
      "publicId": "IMG_6594_nehnni",
      "folder": "Trips",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 1962568,
      "createdAt": "2026-05-09T12:46:04Z"
    },
    {
      "publicId": "IMG_6479_cmdflh",
      "folder": "Trips",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 3655219,
      "createdAt": "2026-05-09T12:46:06Z"
    },
    {
      "publicId": "IMG_6585_cz57hh",
      "folder": "Trips",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 5044520,
      "createdAt": "2026-05-09T12:46:07Z"
    },
    {
      "publicId": "IMG_6763_wvw3kv",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 3966902,
      "createdAt": "2026-05-09T12:46:07Z"
    },
    {
      "publicId": "IMG_6767_zjr5gb",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 3582115,
      "createdAt": "2026-05-09T12:46:09Z"
    },
    {
      "publicId": "IMG_6803_kypztp",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 2157938,
      "createdAt": "2026-05-09T12:46:10Z"
    },
    {
      "publicId": "IMG_6830_lfzzy8",
      "folder": "Trips",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 2332501,
      "createdAt": "2026-05-09T12:46:11Z"
    },
    {
      "publicId": "IMG_6943_gnemfv",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1629759,
      "createdAt": "2026-05-09T12:46:14Z"
    },
    {
      "publicId": "IMG_6945_l3b7ga",
      "folder": "Trips",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1404376,
      "createdAt": "2026-05-09T12:46:15Z"
    },
    {
      "publicId": "IMG_7101_tt7eot",
      "folder": "Trips",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 2727542,
      "createdAt": "2026-05-09T12:46:16Z"
    },
    {
      "publicId": "IMG_7103_sx6q7e",
      "folder": "Trips",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 2693243,
      "createdAt": "2026-05-09T12:46:17Z"
    },
    {
      "publicId": "IMG_7145_tsbjrf",
      "folder": "Trips",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1676851,
      "createdAt": "2026-05-09T12:46:18Z"
    },
    {
      "publicId": "IMG_9346_vpjrkp",
      "folder": "Trips",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 2272884,
      "createdAt": "2026-05-09T12:46:21Z"
    },
    {
      "publicId": "IMG_9352_jnbe1g",
      "folder": "Trips",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 3032327,
      "createdAt": "2026-05-09T12:46:22Z"
    },
    {
      "publicId": "IMG_9349_hjcvoh",
      "folder": "Trips",
      "type": "image",
      "width": 4032,
      "height": 2268,
      "bytes": 1853751,
      "createdAt": "2026-05-09T12:46:22Z"
    },
    {
      "publicId": "IMG_9354_qf8cye",
      "folder": "Trips",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 2934699,
      "createdAt": "2026-05-09T12:46:24Z"
    },
    {
      "publicId": "IMG_9373_dl2dyz",
      "folder": "Trips",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 2153375,
      "createdAt": "2026-05-09T12:46:24Z"
    },
    {
      "publicId": "IMG_9382_v6jjfq",
      "folder": "Trips",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1303376,
      "createdAt": "2026-05-09T12:46:25Z"
    }
  ],
  "In Her Element": [
    {
      "publicId": "IMG_4845_eyircm",
      "folder": "In Her Element",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 2632743,
      "createdAt": "2026-05-09T12:28:51Z"
    },
    {
      "publicId": "IMG_6352_xodozr",
      "folder": "In Her Element",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 324866,
      "createdAt": "2026-05-09T12:29:34Z"
    },
    {
      "publicId": "IMG_6353_v9a40f",
      "folder": "In Her Element",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 329783,
      "createdAt": "2026-05-09T12:29:42Z"
    },
    {
      "publicId": "4a9c3218-d2bf-4b2e-8920-f1a58603146e_v6lgb9",
      "folder": "In Her Element",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 148796,
      "createdAt": "2026-05-09T12:43:45Z"
    },
    {
      "publicId": "9a9819b7-f488-42a1-b8d6-87c4d1e89f73_nd01ez",
      "folder": "In Her Element",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 177915,
      "createdAt": "2026-05-09T12:43:45Z"
    },
    {
      "publicId": "6ef27684-8ae0-4b47-a956-92fbd68c781f_vmfrqf",
      "folder": "In Her Element",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 89863,
      "createdAt": "2026-05-09T12:43:46Z"
    },
    {
      "publicId": "115c4594-d073-4672-9d51-624791a6795d_gxdpg6",
      "folder": "In Her Element",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 75787,
      "createdAt": "2026-05-09T12:43:50Z"
    },
    {
      "publicId": "a0838c88-9ef6-4c2b-ab44-26816f43dc1e_zulkve",
      "folder": "In Her Element",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 187240,
      "createdAt": "2026-05-09T12:43:54Z"
    },
    {
      "publicId": "a8a7f213-3c96-42d1-9b3e-ae2934a6eac9_kvkyiy",
      "folder": "In Her Element",
      "type": "image",
      "width": 1600,
      "height": 1200,
      "bytes": 137885,
      "createdAt": "2026-05-09T12:43:54Z"
    },
    {
      "publicId": "b5146d1a-674d-4656-a6c6-1f93294a598b_jshefe",
      "folder": "In Her Element",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 109050,
      "createdAt": "2026-05-09T12:44:18Z"
    },
    {
      "publicId": "B4A13E31-55CA-415D-B0C8-2CFC0025CC67_gwendu",
      "folder": "In Her Element",
      "type": "image",
      "width": 2160,
      "height": 3840,
      "bytes": 730338,
      "createdAt": "2026-05-09T12:44:22Z"
    },
    {
      "publicId": "d63dbea5-919a-45c2-9c30-babd21744a54_jj3dpp",
      "folder": "In Her Element",
      "type": "video",
      "width": 464,
      "height": 832,
      "bytes": 4005439,
      "createdAt": "2026-05-09T12:44:34Z"
    },
    {
      "publicId": "db48ef7d-694c-4762-ae13-082a06e265e0_dol3fl",
      "folder": "In Her Element",
      "type": "image",
      "width": 720,
      "height": 1280,
      "bytes": 111688,
      "createdAt": "2026-05-09T12:44:35Z"
    },
    {
      "publicId": "f6a790aa-f1f8-4461-a036-963dcb187446_nhfxzo",
      "folder": "In Her Element",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 135306,
      "createdAt": "2026-05-09T12:45:24Z"
    },
    {
      "publicId": "BBC668C2-6527-43B0-9DF3-8B2E9275EF6C_vyvzre",
      "folder": "In Her Element",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 11844050,
      "createdAt": "2026-05-09T12:45:24Z"
    },
    {
      "publicId": "IMG_0181_bbskrl",
      "folder": "In Her Element",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1240261,
      "createdAt": "2026-05-09T12:45:36Z"
    },
    {
      "publicId": "IMG_6193_nkllnx",
      "folder": "In Her Element",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 490260,
      "createdAt": "2026-05-09T12:45:47Z"
    },
    {
      "publicId": "IMG_6192_ibsnjj",
      "folder": "In Her Element",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 466755,
      "createdAt": "2026-05-09T12:45:47Z"
    },
    {
      "publicId": "IMG_6439_noxesm",
      "folder": "In Her Element",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 2561833,
      "createdAt": "2026-05-09T12:45:55Z"
    },
    {
      "publicId": "IMG_6589_smusg4",
      "folder": "In Her Element",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 322583,
      "createdAt": "2026-05-09T12:46:02Z"
    },
    {
      "publicId": "IMG_6870_vvveql",
      "folder": "In Her Element",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 3002751,
      "createdAt": "2026-05-09T12:46:12Z"
    },
    {
      "publicId": "IMG_6896_qld3il",
      "folder": "In Her Element",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1663820,
      "createdAt": "2026-05-09T12:46:12Z"
    },
    {
      "publicId": "IMG_6899_jerftg",
      "folder": "In Her Element",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1757520,
      "createdAt": "2026-05-09T12:46:13Z"
    },
    {
      "publicId": "IMG_8244_fntm7w",
      "folder": "In Her Element",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1901209,
      "createdAt": "2026-05-09T12:46:19Z"
    },
    {
      "publicId": "IMG_2885_hzqkds",
      "folder": "In Her Element",
      "type": "video",
      "width": 2160,
      "height": 3840,
      "bytes": 29537790,
      "createdAt": "2026-05-09T12:46:29Z"
    },
    {
      "publicId": "IMG_6377_z4j207",
      "folder": "In Her Element",
      "type": "video",
      "width": 2160,
      "height": 3840,
      "bytes": 32239019,
      "createdAt": "2026-05-09T12:46:32Z"
    },
    {
      "publicId": "IMG_0052_ygwpeo",
      "folder": "In Her Element",
      "type": "video",
      "width": 1080,
      "height": 1920,
      "bytes": 70338792,
      "createdAt": "2026-05-09T12:46:39Z"
    },
    {
      "publicId": "filtered-8551B2F1-CB64-4CDF-91EF-5443617B5178_xa5gjb",
      "folder": "In Her Element",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 8888401,
      "createdAt": "2026-05-09T13:19:54Z"
    }
  ],
  "Where it All Began": [
    {
      "publicId": "ca418172-a635-4b48-9e5b-b18e6b32e809_ruwmeq",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1200,
      "height": 1600,
      "bytes": 203921,
      "createdAt": "2026-05-09T12:29:03Z"
    },
    {
      "publicId": "IMG_6026_famoxy",
      "folder": "Where it All Began",
      "type": "image",
      "width": 2208,
      "height": 1244,
      "bytes": 477446,
      "createdAt": "2026-05-09T12:29:37Z"
    },
    {
      "publicId": "66b1a769-d856-4654-ba7c-3c53a5b4ec15_lsxmsk",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1600,
      "height": 1200,
      "bytes": 381549,
      "createdAt": "2026-05-09T12:29:37Z"
    },
    {
      "publicId": "9da79b54-46d5-4436-8660-30cbb1a0d45b_lfafy5",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1600,
      "height": 1200,
      "bytes": 266388,
      "createdAt": "2026-05-09T12:43:46Z"
    },
    {
      "publicId": "50bdb122-582e-483f-b848-78498dbd2446_thx0rw",
      "folder": "Where it All Began",
      "type": "image",
      "width": 3000,
      "height": 4000,
      "bytes": 1091674,
      "createdAt": "2026-05-09T12:43:49Z"
    },
    {
      "publicId": "828c5f7a-c395-403e-b18c-b55ae9338221_owsn9z",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1200,
      "height": 1600,
      "bytes": 475303,
      "createdAt": "2026-05-09T12:43:52Z"
    },
    {
      "publicId": "9900d49f-5c43-4fdc-b53f-6379bcd52572_uwe9hu",
      "folder": "Where it All Began",
      "type": "image",
      "width": 3000,
      "height": 4000,
      "bytes": 1425704,
      "createdAt": "2026-05-09T12:43:53Z"
    },
    {
      "publicId": "494399be-9da5-4aad-9d47-81d822bf1b64_jd9mxr",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1200,
      "height": 1600,
      "bytes": 288558,
      "createdAt": "2026-05-09T12:43:54Z"
    },
    {
      "publicId": "b467dfbf-b2be-4605-8541-7fe7a18609e6_nig4su",
      "folder": "Where it All Began",
      "type": "image",
      "width": 3000,
      "height": 4000,
      "bytes": 1081511,
      "createdAt": "2026-05-09T12:44:20Z"
    },
    {
      "publicId": "ca418172-a635-4b48-9e5b-b18e6b32e809_w1zcjw",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1200,
      "height": 1600,
      "bytes": 203921,
      "createdAt": "2026-05-09T12:44:23Z"
    },
    {
      "publicId": "IMG_0061_uhqsxx",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1547320,
      "createdAt": "2026-05-09T12:45:32Z"
    },
    {
      "publicId": "IMG_0088_tvagj3",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1126373,
      "createdAt": "2026-05-09T12:45:33Z"
    },
    {
      "publicId": "IMG_0062_f25tad",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1520845,
      "createdAt": "2026-05-09T12:45:33Z"
    },
    {
      "publicId": "IMG_0177_bquwrg",
      "folder": "Where it All Began",
      "type": "image",
      "width": 2268,
      "height": 4032,
      "bytes": 2691393,
      "createdAt": "2026-05-09T12:45:35Z"
    },
    {
      "publicId": "IMG_8422_yytiqf",
      "folder": "Where it All Began",
      "type": "image",
      "width": 1242,
      "height": 2208,
      "bytes": 361747,
      "createdAt": "2026-05-09T12:46:19Z"
    }
  ],
  "Generic": [
    {
      "publicId": "2f851225-210d-4512-ad14-dd59ebebea1f_rhua5t",
      "folder": "Generic",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 222113,
      "createdAt": "2026-05-09T12:43:15Z"
    },
    {
      "publicId": "22c1c739-8d5b-460f-8dce-b5a222a6ccc2_ukhdxn",
      "folder": "Generic",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 253506,
      "createdAt": "2026-05-09T12:43:47Z"
    },
    {
      "publicId": "adb67dd4-77a3-4bf3-9a19-e2646d154f16_tssegv",
      "folder": "Generic",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 197614,
      "createdAt": "2026-05-09T12:44:18Z"
    },
    {
      "publicId": "e150e941-a2e1-4c8e-9362-369155fd791c_gbc2ul",
      "folder": "Generic",
      "type": "image",
      "width": 2295,
      "height": 4080,
      "bytes": 753761,
      "createdAt": "2026-05-09T12:45:18Z"
    },
    {
      "publicId": "f3f5e3f3-7d6c-4320-a36e-9de2f2fb6a7c_y1ovzp",
      "folder": "Generic",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 180040,
      "createdAt": "2026-05-09T12:45:22Z"
    },
    {
      "publicId": "f812fc3a-ed9c-4b12-beec-1e103e8f5ab8_t5ownc",
      "folder": "Generic",
      "type": "image",
      "width": 960,
      "height": 1280,
      "bytes": 234209,
      "createdAt": "2026-05-09T12:45:25Z"
    },
    {
      "publicId": "IMG_2267_d5e31d",
      "folder": "Generic",
      "type": "image",
      "width": 1737,
      "height": 3088,
      "bytes": 1850083,
      "createdAt": "2026-05-09T12:45:37Z"
    },
    {
      "publicId": "IMG_2857_qlrqwe",
      "folder": "Generic",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 3271141,
      "createdAt": "2026-05-09T12:45:38Z"
    },
    {
      "publicId": "IMG_2882_ncnguk",
      "folder": "Generic",
      "type": "image",
      "width": 4284,
      "height": 5712,
      "bytes": 3828960,
      "createdAt": "2026-05-09T12:45:40Z"
    },
    {
      "publicId": "dcc4eab7-e7fc-4fea-82cf-203779695b48_d70xzc",
      "folder": "Generic",
      "type": "image",
      "width": 900,
      "height": 1600,
      "bytes": 188431,
      "createdAt": "2026-05-09T12:46:44Z"
    }
  ],
  "Coldplay": [
    {
      "publicId": "725c36bf-b1ee-46f4-a9b5-f19ea53c10dc_c5vo6m",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1301117,
      "createdAt": "2026-05-09T12:43:20Z"
    },
    {
      "publicId": "85131a51-d94f-4f48-8027-1d7a953c5c8f_grb8hf",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1372990,
      "createdAt": "2026-05-09T12:43:20Z"
    },
    {
      "publicId": "70c57e70-855e-447c-9c2b-bc2d0aba082d_d4qelg",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1282114,
      "createdAt": "2026-05-09T12:43:21Z"
    },
    {
      "publicId": "3eb1e8d4-1e7c-4b11-a39b-c92d4a272775_n39fcl",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1465635,
      "createdAt": "2026-05-09T12:43:21Z"
    },
    {
      "publicId": "53e91b5d-726c-4ae9-bb43-0fd050d0bb5a_vawji7",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1463490,
      "createdAt": "2026-05-09T12:43:23Z"
    },
    {
      "publicId": "719ba0d7-2ea2-4862-bf45-4c3ef4fa07fd_ezrawv",
      "folder": "Coldplay",
      "type": "image",
      "width": 3120,
      "height": 4160,
      "bytes": 2417788,
      "createdAt": "2026-05-09T12:43:24Z"
    },
    {
      "publicId": "3eb1e8d4-1e7c-4b11-a39b-c92d4a272775_bgknp2",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1465635,
      "createdAt": "2026-05-09T12:43:45Z"
    },
    {
      "publicId": "21a5fd09-1487-43ec-9b26-454f0ac292ae_bt4xi1",
      "folder": "Coldplay",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1353139,
      "createdAt": "2026-05-09T12:43:46Z"
    },
    {
      "publicId": "38a423d9-d3f4-47e3-a1dc-1517c4688e83_ivobna",
      "folder": "Coldplay",
      "type": "image",
      "width": 2252,
      "height": 4000,
      "bytes": 1207346,
      "createdAt": "2026-05-09T12:43:47Z"
    },
    {
      "publicId": "43bdf709-5b10-479c-a631-e9960c06af7e_pvtc1t",
      "folder": "Coldplay",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 1582658,
      "createdAt": "2026-05-09T12:43:47Z"
    },
    {
      "publicId": "70c57e70-855e-447c-9c2b-bc2d0aba082d_hbvddm",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1282114,
      "createdAt": "2026-05-09T12:43:49Z"
    },
    {
      "publicId": "58f5e5fc-1f77-4be1-9923-8f45a1db94e7_hbsbuj",
      "folder": "Coldplay",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 1600633,
      "createdAt": "2026-05-09T12:43:49Z"
    },
    {
      "publicId": "129f7d0d-5ebd-4d38-86d2-1eb0696e72bc_poxjgc",
      "folder": "Coldplay",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1575471,
      "createdAt": "2026-05-09T12:43:50Z"
    },
    {
      "publicId": "258a90b9-2e8e-45d9-8efb-3e5eea930cbe_evr3nl",
      "folder": "Coldplay",
      "type": "image",
      "width": 2316,
      "height": 3088,
      "bytes": 1010539,
      "createdAt": "2026-05-09T12:43:51Z"
    },
    {
      "publicId": "8612be79-646a-4126-9fda-e86aa0f39c8a_x83ooi",
      "folder": "Coldplay",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 1618107,
      "createdAt": "2026-05-09T12:43:53Z"
    },
    {
      "publicId": "c47efeba-b0ac-48b6-b7a1-18034e9f72ab_gndoc1",
      "folder": "Coldplay",
      "type": "video",
      "width": 1280,
      "height": 720,
      "bytes": 1433956,
      "createdAt": "2026-05-09T12:44:23Z"
    },
    {
      "publicId": "d57a491e-88cc-46cb-a50d-c96c20721012_rqebqz",
      "folder": "Coldplay",
      "type": "image",
      "width": 1818,
      "height": 4029,
      "bytes": 1116713,
      "createdAt": "2026-05-09T12:44:33Z"
    },
    {
      "publicId": "d09799a6-0abb-433e-8bf9-7ad35df63984_tzhtrv",
      "folder": "Coldplay",
      "type": "image",
      "width": 3120,
      "height": 4160,
      "bytes": 2620072,
      "createdAt": "2026-05-09T12:44:35Z"
    },
    {
      "publicId": "db2813c9-11be-4ca9-92ef-c082b288f645_nutqjx",
      "folder": "Coldplay",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 905994,
      "createdAt": "2026-05-09T12:45:15Z"
    },
    {
      "publicId": "ff2d39da-63da-46b9-9e63-d39a52863f3a_syr6d2",
      "folder": "Coldplay",
      "type": "image",
      "width": 3120,
      "height": 4160,
      "bytes": 2138560,
      "createdAt": "2026-05-09T12:45:27Z"
    },
    {
      "publicId": "fa112b4e-3f9e-494b-95bc-010a6b2022c5_vprsm2",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 987241,
      "createdAt": "2026-05-09T12:45:27Z"
    },
    {
      "publicId": "d79a7a5b-8920-4d74-988b-8101c7592876_atnqtv",
      "folder": "Coldplay",
      "type": "image",
      "width": 3024,
      "height": 4032,
      "bytes": 1693949,
      "createdAt": "2026-05-09T12:46:44Z"
    },
    {
      "publicId": "db3ace7e-c7de-4829-a49e-e72a76143b0b_jrw3y2",
      "folder": "Coldplay",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 1703985,
      "createdAt": "2026-05-09T12:46:45Z"
    },
    {
      "publicId": "175272e7-77af-4e84-82ad-7c72d0798621_iqq08e",
      "folder": "Coldplay",
      "type": "image",
      "width": 4032,
      "height": 3024,
      "bytes": 1402735,
      "createdAt": "2026-05-09T13:53:11Z"
    },
    {
      "publicId": "47088be6-a5f0-4646-92a6-584f6e5ad667_lxcavu",
      "folder": "Coldplay",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 2722637,
      "createdAt": "2026-05-09T13:53:40Z"
    },
    {
      "publicId": "891e606b-8cf4-4704-833b-6ad333807566_raoavh",
      "folder": "Coldplay",
      "type": "video",
      "width": 720,
      "height": 1280,
      "bytes": 9388110,
      "createdAt": "2026-05-09T13:53:45Z"
    }
  ]
};

export function assetsInFolder(folder: string): CldAsset[] {
  return cldByFolder[folder] ?? [];
}
